language: php
dist: trusty
php: 7.2
git:
  depth: 3
cache:
  directories:
    - ~/config-check
install:
- mkdir ~/config-check || true
- composer create-project idrinth/config-check --no-dev --working-dir=~/config-check -q || composer update  --no-dev --working-dir=~/config-check -q
script: php ~/config-check/check-config -vvv -w
