language: php
dist: trusty
php: 7.2
git:
  depth: 3
cache:
  directories:
    - /home/travis/check
install:
- mkdir /home/travis/check || true
- composer update --no-dev --working-dir=/home/travis/check || composer create-project --stability=dev --no-dev --working-dir=/home/travis/check -- idrinth/config-check /home/travis/check dev-master
script:
- php /home/travis/check/check-config -vvv -w
