git:
  depth: 3  
cache:
  directories:
  - ~/.composer/cache/
  - ~/.npm

jobs:
  include:
  - language: php
    php: 7.2
    stage: Linting
    name: Config
    install:
    - mkdir /home/travis/check || true
    - composer update --no-dev --working-dir=/home/travis/check || composer create-project --stability=dev --no-dev --working-dir=/home/travis/check -- idrinth/config-check /home/travis/check dev-master
    script:
    - php /home/travis/check/check-config -w
  - language: node_js
    node_js: node
    stage: Linting
    name: Eslint
    install:
    - npm i -g eslint
    script:
    - eslint main.js
