language: php
dist: trusty
php: 7.2
git:
  depth: 3
cache:
  directories:
    - ~/config-check
install:
- mkdir /home/travis/config-check || true
- composer create-project idrinth/config-check --stability=dev --no-dev --working-dir=/home/travis/config-check || composer update --no-dev --working-dir=/home/travis/config-check
script:
- php ~/config-check/check-config -vvv -w
